### ISSUE TITLE
Confusion with Teacher Tokens

### ISSUE THREAD

**Issue by SXKJames** [caddyless/PCAE#1]
Hello,

In your paper, the teacher network is supposed to operate on masked tokens while the student network operates on visible tokens. However, I believe in your code, both networks operate on visible tokens.  

This is because within models_mae.py the teacher network is called as such:
```python

  def forward_teacher(self, x, mask_ratio, drop_stage=3, drop_case=0, keep_ratio=0.5, random_drop=False):
          # embed patches
          x = self.patch_embed(x)
  
          # add pos embed w/o cls token
          x = x + self.pos_embed[:, 1:, :]
  
          x, student_ids_keep, teacher_ids_keep = self.random_masking(x, mask_ratio=mask_ratio)
```

However, the output of `self.random_masking` is defined as `x` masked with `student_ids_keep` not `teacher_ids_keep`

```python
  def random_masking(self, x, mask_ratio):
        """
        Perform per-sample random masking by per-sample shuffling.
        Per-sample shuffling is done by argsort random noise.
        x: [N, L, D], sequence
        """
      
        ....
        # split patches into ids_keep and ids_remove
        ids_keep = ids_shuffle[:, :len_keep]
        ids_remove = ids_shuffle[:, len_keep:]
        x_masked = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, D))


        return x_masked, ids_keep, ids_remove
```

The  student network also uses `student_ids_keep` to mask tokens: 

```python
latent = model(samples, student_ids_keep=student_ids_keep, teacher_ids_keep=teacher_ids_keep) # from engine_pretrain.py
def forward_student(self, x, ids_keep, teacher_ids_keep):
        # embed patches
        x = self.patch_embed(x)
        # add pos embed w/o cls token
        x = x + self.pos_embed[:, 1:, :]

        # masking: length -> length * mask_ratio
        x = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, x.size(-1)))

```

As a results, both networks operate on visible patches. 

Could you confirm that this is a typo or that I am misunderstanding your code.

Thank you

**Comment by caddyless** [comment]
Hello,

I checked my implementation and found that it is a typo here. As you say, the definition of x_masked is supposed to be:

    x_masked = torch.gather(x, dim=1, index=ids_remove.unsqueeze(-1).repeat(1, 1, D))

instead of

    x_masked = torch.gather(x, dim=1, index=ids_keep.unsqueeze(-1).repeat(1, 1, D))

Sincerely appreciate your patience and we will fix this as soon as possible.

**Comment by SXKJames** [comment]
Thanks! That clears everything up.
